let print_stanza bin name =
  print_string [%string {|

; %{name}

(rule
  (alias "%{name}.elab")
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.elab.stdout.exp
        (run %{bin} elab)))))

(rule
  (alias "%{name}.norm")
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.norm.stdout.exp
        (run %{bin} norm)))))

(rule (alias runtest)
  (action (diff expected/%{name}.elab.stdout
                %{name}.elab.stdout.exp)))

(rule (alias runtest)
  (action (diff expected/%{name}.norm.stdout
                %{name}.norm.stdout.exp)))
|}]


let () =
  match Array.to_list Sys.argv with
  | _ :: bin :: test_names ->
      print_endline "; @generated by `dune build --auto-promote`";
      List.iter (print_stanza ("%{bin:" ^ bin ^ "}")) test_names
  | _ -> failwith "bad args"
