let print_stanza name =
  print_string [%string {|

; %{name}

(rule
  (alias "%{name}.elab")
  (package mltt)
  (deps ../main.exe)
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.elab.stdout.exp
        (run mltt elab)))))

(rule
  (alias "%{name}.norm")
  (package mltt)
  (deps ../main.exe)
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.norm.stdout.exp
        (run mltt norm)))))

(rule
  (alias runtest)
  (package mltt)
  (deps (alias %{name}.elab))
  (action
    (diff expected/%{name}.elab.stdout %{name}.elab.stdout.exp)))

(rule
  (alias runtest)
  (package mltt)
  (deps (alias %{name}.norm))
  (action
    (diff expected/%{name}.norm.stdout %{name}.norm.stdout.exp)))
|}]


let () =
  match Array.to_list Sys.argv with
  | _ :: test_names ->
      print_endline "; @generated by `dune build --auto-promote`";
      List.iter print_stanza test_names
  | _ -> failwith "bad args"
