let print_stanza name =
  print_string [%string {|

; %{name}

(rule
  (deps ../main.exe)
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.elab.stdout.exp
        (run mltt elab)))))

(rule
  (deps ../main.exe)
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.norm.stdout.exp
        (run mltt norm)))))

(rule
  (alias runtest)
  (action
    (diff %{name}.elab.stdout %{name}.elab.stdout.exp)))

(rule
  (alias runtest)
  (action
    (diff %{name}.norm.stdout %{name}.norm.stdout.exp)))
|}]


let () =
  let args = Array.sub Sys.argv 1 (Array.length Sys.argv - 1) in

  print_endline "; @generated by `dune build --auto-promote`";

  Array.iter print_stanza args
