let print_stanza package name =
  print_string [%string {|

; %{name}

(rule
  (alias "%{name}.elab")
  (package %{package})
  (deps ../main.exe)
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.elab.stdout.exp
        (run %{package} elab)))))

(rule
  (alias "%{name}.norm")
  (package %{package})
  (deps ../main.exe)
  (action
    (with-stdin-from %{name}
      (with-stdout-to %{name}.norm.stdout.exp
        (run %{package} norm)))))

(rule
  (alias runtest)
  (package %{package})
  (deps (alias %{name}.elab))
  (action
    (diff expected/%{name}.elab.stdout %{name}.elab.stdout.exp)))

(rule
  (alias runtest)
  (package %{package})
  (deps (alias %{name}.norm))
  (action
    (diff expected/%{name}.norm.stdout %{name}.norm.stdout.exp)))
|}]


let () =
  match Array.to_list Sys.argv with
  | _ :: package :: test_names ->
      print_endline "; @generated by `dune build --auto-promote`";
      List.iter (print_stanza package) test_names
  | _ -> failwith "bad args"
